version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    container_name: petrvs_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql      # Define um volume persistente para os dados do MariaDB
      - ./my.cnf:/etc/mysql/my.cnf  # Certifique-se que este arquivo est√° corretamente configurado
    environment:
      MYSQL_ROOT_PASSWORD: rootpgd   # Define a senha para o root
  petrvs_php:
    image: segescginf/pgdpetrvs:latest  # Substitua pela sua imagem real
    container_name: petrvs_php
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4048M
    volumes:
      - "./.env:/var/www/.env"
      - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini
  petrvs_queue:
    image: segescginf/pgdpetrvs:latest
    container_name: petrvs_queue
    environment:
      - TZ=America/Bahia
    command: ["/bin/bash", "-c", "mkdir -p /var/www/storage/logs && chown -R www-data:www-data /var/www/storage && chmod -R 775 /var/www/storage && supervisord -c /etc/supervisor/conf.d/horizon.conf"]
    depends_on:
      - petrvs_php
    volumes:
      - "./.env:/var/www/.env"
      - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    stdin_open: true
    tty: true
  petrvs_redis:
    image: redis:alpine
    container_name: petrvs_redis
    ports:
      - "6379:6379"
volumes:
  db_data:  # Declara o volume persistente